eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 22222

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/high-five}
      database: high-five
      uuid-representation: standard
  datasource:
    url: jdbc:postgresql://localhost:5432/high-five
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      platform: postgres
