
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

server:
  port: 22222

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: ${DB_2_URI:mongodb://localhost:27017/high-five}
      database: high-five
      uuid-representation: standard
  datasource:
    url: ${DB_1_URL:jdbc:postgresql://localhost:5432/high-five}
    username: ${DB_1_USERNAME:postgres}
    password: ${DB_2_PASSWORD:postgres}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: guest
    password: guest
    virtual-host: /

  sql:
    init:
      mode: always
      platform: postgres
