eureka:
  client:
    enabled: false
logging:
  level:
    '[org.springframework.data.mongodb.core]': DEBUG

server:
  port: 8080

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/high-five}
      database: high-five
      uuid-representation: standard
  datasource:
    url: jdbc:postgresql://localhost:5434/high-five
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      platform: postgres
